---
title: "Suivi de la croissance de la salicorne"
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,fig.align="center")
require(tidyverse)
require(plotly)
require(lubridate)
```

### 27/05/2020

```{r S27052020plot}
S27052020 <- readxl::read_xlsx("./data/culture_Intechmer/fichier_donnees_culture.xlsx",sheet="27052020")
S27052020 <- S27052020 %>% gather(-taille,key="bac",value="nombre") %>% drop_na() %>% group_by(bac) %>% mutate(nbPourc=(nombre/sum(nombre))*100)
S27052020$taille <- factor(S27052020$taille,c("< 1cm","]1;2cm]","]2;4cm]","]4;6cm]","]6;8cm]"),ordered=T)
ggplot(S27052020,aes(x=taille,y=nbPourc))+geom_bar(stat="identity")+facet_wrap(~bac,ncol=3)+
  ylab("Pourcentage")+xlab("Classes de taille")+
  theme(strip.text = element_text(face="bold",size=10),
        axis.title = element_text(face="italic",size=12),
        axis.text.x = element_text(angle=90,vjust=0.5))
```

### 10/06/2020

```{r S10062020plot}
S10062020 <- readxl::read_xlsx("./data/culture_Intechmer/fichier_donnees_culture.xlsx",sheet="10062020")
S10062020 <- S10062020 %>% gather(-taille,key="bac",value="nombre") %>% drop_na() %>% group_by(bac) %>% mutate(nbPourc=(nombre/sum(nombre))*100)
S10062020$taille <- factor(S10062020$taille,c("< 1cm","]1;2cm]","]2;4cm]","]4;6cm]","]6;8cm]","]8;10cm]"),ordered=T)
ggplot(S10062020,aes(x=taille,y=nbPourc))+geom_bar(stat="identity")+facet_wrap(~bac,ncol=3)+
  ylab("Pourcentage")+xlab("Classes de taille")+
  theme(strip.text = element_text(face="bold",size=10),
        axis.title = element_text(face="italic",size=12),
        axis.text.x = element_text(angle=90,vjust=0.5))
```


### 29/06/2020

```{r S29062020plot}
S29062020 <- readxl::read_xlsx("./data/culture_Intechmer/fichier_donnees_culture.xlsx",sheet="29062020")
S29062020 <- S29062020 %>% gather(-taille,key="bac",value="nombre") %>% drop_na() %>% group_by(bac) %>% mutate(nbPourc=(nombre/sum(nombre))*100)
S29062020$taille <- factor(S29062020$taille,c("< 1cm","]1;2cm]","]2;4cm]","]4;6cm]","]6;8cm]","]8;10cm]","]10;12cm]","]12;14cm]","]14;16cm]","]16;18cm]","]18;20cm]",
                                              "]20;22cm]","]22;24cm]","]24;26cm]"),ordered=T)
ggplot(S29062020,aes(x=taille,y=nbPourc))+geom_bar(stat="identity")+facet_wrap(~bac,ncol=3)+
  ylab("Pourcentage")+xlab("Classes de taille")+
  theme(strip.text = element_text(face="bold",size=10),
        axis.title = element_text(face="italic",size=12),
        axis.text.x = element_text(angle=90,vjust=0.5))
```


### 24/07/2020

```{r S24072020plot}
S24072020 <- readxl::read_xlsx("./data/culture_Intechmer/fichier_donnees_culture.xlsx",sheet="24072020")
S24072020 <- S24072020 %>% gather(-taille,key="bac",value="nombre") %>% drop_na() %>% group_by(bac) %>% mutate(nbPourc=(nombre/sum(nombre))*100)
S24072020$taille <- factor(S24072020$taille,c("< 1cm","]1;2cm]","]2;4cm]","]4;6cm]","]6;8cm]","]8;10cm]","]10;12cm]","]12;14cm]","]14;16cm]","]16;18cm]","]18;20cm]",
                                              "]20;22cm]","]22;24cm]","]24;26cm]","]26;28cm]","]28;30cm]","]30;32cm]",
                              "]32;34cm]","]34;36cm]","]36;38cm]","]38;40cm]"),ordered=T)
ggplot(S24072020,aes(x=taille,y=nbPourc))+geom_bar(stat="identity")+facet_wrap(~bac,ncol=3)+
  ylab("Pourcentage")+xlab("Classes de taille")+
  theme(strip.text = element_text(face="bold",size=10),
        axis.title = element_text(face="italic",size=12),
        axis.text.x = element_text(angle=90,vjust=0.5))
```

### 24/08/2020

```{r S24082020plot}
S24082020 <- readxl::read_xlsx("./data/culture_Intechmer/fichier_donnees_culture.xlsx",sheet="24082020")
S24082020 <- S24082020 %>% gather(-taille,key="bac",value="nombre") %>% drop_na() %>% group_by(bac) %>% mutate(nbPourc=(nombre/sum(nombre))*100)
S24082020$taille <- factor(S24082020$taille,c("< 1cm","]1;2cm]","]2;4cm]","]4;6cm]","]6;8cm]","]8;10cm]","]10;12cm]","]12;14cm]","]14;16cm]","]16;18cm]","]18;20cm]","]20;22cm]","]22;24cm]","]24;26cm]","]26;28cm]","]28;30cm]","]30;32cm]","]32;34cm]","]34;36cm]","]36;38cm]","]38;40cm]","]40;42cm]","]42;44cm]","]44;46cm]","]46;48cm]","]48;50cm]","]50;52cm]"),ordered=T)
ggplot(S24082020,aes(x=taille,y=nbPourc))+geom_bar(stat="identity")+facet_wrap(~bac,ncol=3)+
  ylab("Pourcentage")+xlab("Classes de taille")+
  theme(strip.text = element_text(face="bold",size=10),
        axis.title = element_text(face="italic",size=12),
        axis.text.x = element_text(angle=90,vjust=0.5))
```